# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 967cd20091e7e2fd437dae61047782563839318deb3bf6111b5fbc1cacd1a5a80b9de877b95ab1dfa3b34a45a5128c74ef419688ffd5b4d68f4772de4e50d6a7

test:
  secret_key_base: 9d046fc0acf32d98644486d3b2ae656ac42a8bb01fec09f874c35db262400bac3afa6a5635714679910189b4307d753c8d9a1a9bbcb8fa79879d8c5ffb103af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
